-- This file contains replacements for custom weapons, because better implementations are available.
-- The replacements currently use http://steamcommunity.com/sharedfiles/filedetails/?id=108720350, 
-- http://steamcommunity.com/sharedfiles/filedetails/?id=254077907,
-- https://steamcommunity.com/sharedfiles/filedetails/?id=275002520 and M9K weapons.
OC.CustomReplacements = {
	custom_ak47 = "bb_ak47_alt",
	custom_ak47new = "bb_ak47_alt",
	custom_ak47new_de_prodigy = "bb_ak47_alt",
	custom_ak5 = "m9k_fal",
	custom_aug = "bb_aug_alt",
	custom_awp = "bb_awp_alt",
	custom_cz52 = {"weapon_cz52", "bb_p228_alt"},
	custom_deagle = "bb_deagle_alt",
	custom_elite = "bb_dualelites_alt",
	custom_famas = "bb_famas_alt",
	custom_fiveseven = "bb_fiveseven_alt",
	custom_g3 = {"m9k_g3a3", "bb_m4a1_alt"},
	custom_g36c = {"m9k_g36", "bb_galil_alt"},
	custom_galil = "bb_galil_alt",
	custom_glock = "bb_glock_alt",
	custom_hmg1 = "weapon_bp_hmg1",
	custom_m249 = "bb_m249_alt",
	custom_m3 = "bb_m3_alt",
	custom_m4new = "bb_m4a1_alt",
	custom_m4new_de_prodigy = "bb_m4a1_alt",
	custom_mac10 = "bb_mac10_alt",
	custom_mp5k = "bb_mp5_alt",
	custom_mp5_de_prodigy = "bb_mp5_alt",
	custom_oicw = "weapon_bp_oicw",
	custom_p228 = "bb_p228_alt",
	custom_p90 = "bb_p90_alt",
	custom_remi870 = {"m9k_remington870", "bb_xmp1014_alt"},
	custom_scout = "bb_scout_alt",
	custom_sg550 = "bb_sg550_alt",
	custom_sg552 = "bb_sg552_alt",
	custom_spas12 = {"m9k_spas12", "weapon_shotgun"},
	--custom_tang = "",
	custom_tmp = "bb_tmp_alt",
	custom_ump45 = "bb_ump45_alt",
	custom_usp = "bb_usp_alt",
	custom_xm1014 = "bb_xmp1014_alt",
	weapon_hopwire = "weapon_bp_hopwire",
	weapon_sniperrifle = "weapon_bp_sniper",
	weapon_flaregun = "weapon_bp_flaregun"
}

OC.NPCReplacements = {
}