-- This file is auto-generated. DO NOT TOUCH!
sound.Add({ name="Default.ClipEmpty_Pistol", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/ClipEmpty_Pistol.wav" })
sound.Add({ name="Default.ClipEmpty_Rifle", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/ClipEmpty_Rifle.wav" })
sound.Add({ name="Default.Zoom", channel=CHAN_ITEM, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/zoom.wav" })
sound.Add({ name="Weapon_AK47.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/ak47/ak47-1.wav" })
sound.Add({ name="Weapon_AR2.NPC_Reload", channel=CHAN_ITEM, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/ar2/npc_ar2_reload.wav" })
sound.Add({ name="Weapon_AR2.Reload", channel=CHAN_ITEM, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/ar2/ar2_reload.wav" })
sound.Add({ name="Weapon_AWP.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/awp/awp1.wav" })
sound.Add({ name="Weapon_AUG.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/aug/aug-1.wav" })
sound.Add({ name="Weapon_CombineGuard.Special1", channel=CHAN_WEAPON, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/cguard/charging.wav" })
sound.Add({ name="Weapon_DEagle.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/DEagle/deagle-1.wav" })
sound.Add({ name="Weapon_FiveSeven.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/fiveseven/fiveseven-1.wav" })
sound.Add({ name="Weapon_IRifle.Empty", channel=CHAN_WEAPON, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/ar2/ar2_empty.wav" })
sound.Add({ name="Weapon_M249.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/m249/m249-1.wav" })
sound.Add({ name="Weapon_M3.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/m3/m3-1.wav" })
sound.Add({ name="Weapon_M4A1.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/m4a1/m4a1_unsil-1.wav" })
sound.Add({ name="Weapon_MAC10.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/mac10/mac10-1.wav" })
sound.Add({ name="Weapon_OICW.Empty", channel=CHAN_WEAPON, pitch=1, volume=1.0, level = SNDLVL_NORM, sound = "weapons/oicw/ar2_empty.wav" })
sound.Add({ name="Weapon_OICW.NPC_Reload", channel=CHAN_ITEM, pitch=1, volume=1.0, level = SNDLVL_NORM, sound = "weapons/oicw/npc_ar2_reload.wav" })
sound.Add({ name="Weapon_OICW.Reload", channel=CHAN_ITEM, pitch=1, volume=1.0, level = SNDLVL_NORM, sound = "weapons/oicw/ar2_reload.wav" })

sound.Add({ name="Weapon_OICW.Special1", channel=CHAN_WEAPON, pitch=1, volume=1.0, level = SNDLVL_NORM, sound = "weapons/sniper/sniper_zoomin.wav" })
sound.Add({ name="Weapon_OICW.Special2", channel=CHAN_WEAPON, pitch=1, volume=1.0, level = SNDLVL_NORM, sound = "weapons/sniper/sniper_zoomout.wav" })

sound.Add({ name="Weapon_P228.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/p228/p228-1.wav" })
sound.Add({ name="Weapon_Pistol.Burst", channel=CHAN_WEAPON, pitch={98,105}, volume=0.7, level = SNDLVL_GUNFIRE, sound = "weapons/smg1/smg1_fireburst1.wav" })
sound.Add({ name="Weapon_Pistol.Empty", channel=CHAN_WEAPON, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/pistol/pistol_empty.wav" })
sound.Add({ name="Weapon_Pistol.NPC_Reload", channel=CHAN_ITEM, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/smg1/smg1_reload.wav" })
sound.Add({ name="Weapon_Pistol.Special1", channel=CHAN_WEAPON, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/smg1/switch_single.wav" })
sound.Add({ name="Weapon_Pistol.Special2", channel=CHAN_WEAPON, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/smg1/switch_burst.wav" })
sound.Add({ name="Weapon_SG550.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/sg550/sg550-1.wav" })
sound.Add({ name="Weapon_SG552.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/sg552/sg552-1.wav" })
sound.Add({ name="Weapon_SMG1.Burst", channel=CHAN_WEAPON, pitch={98,105}, volume=0.7, level = SNDLVL_GUNFIRE, sound = "weapons/smg1/smg1_fire1.wav" })
sound.Add({ name="Weapon_SMG1.Empty", channel=CHAN_WEAPON, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/pistol/pistol_empty.wav" })
sound.Add({ name="Weapon_SMG1.NPC_Reload", channel=CHAN_ITEM, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/smg1/smg1_reload.wav" })
sound.Add({ name="Weapon_SMG1.Reload", channel=CHAN_ITEM, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/smg1/smg1_reload.wav" })
sound.Add({ name="Weapon_SMG1.Single", channel=CHAN_WEAPON, pitch={95,105}, volume=0.55, level = SNDLVL_GUNFIRE, sound = "weapons/smg1/smg1_pl_fire.wav" })
sound.Add({ name="Weapon_SMG1.Special1", channel=CHAN_WEAPON, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/smg1/switch_single.wav" })
sound.Add({ name="Weapon_SMG1.Special2", channel=CHAN_WEAPON, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/smg1/switch_burst.wav" })
sound.Add({ name="Weapon_Scout.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/scout/scout_fire-1.wav" })
sound.Add({ name="Weapon_Shotgun.Empty", channel=CHAN_WEAPON, pitch={95,100}, volume=0.7, level = SNDLVL_NORM, sound = "weapons/shotgun/shotgun_empty.wav" })

sound.Add({ name="Weapon_SniperRifle.NPC_Reload", channel=CHAN_ITEM, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "npc/sniper/reload1.wav" })
sound.Add({ name="Weapon_TMP.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/tmp/tmp-1.wav" })
sound.Add({ name="Weapon_UMP45.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/ump45/ump45-1.wav" })
sound.Add({ name="Weapon_USP.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/usp/usp_unsil-1.wav" })
sound.Add({ name="Weapon_ak5.Single", channel=CHAN_WEAPON, pitch={100,105}, volume=0.9, level = SNDLVL_GUNFIRE, sound = "weapons/ak5/fire.wav" })
sound.Add({ name="Weapon_cz52.Reload", channel=CHAN_ITEM, pitch=1, volume=1.0, level = SNDLVL_NORM, sound = "weapons/cz52/reload.wav" })
sound.Add({ name="Weapon_cz52.Single", channel=CHAN_WEAPON, pitch={118,121}, volume=0.95, level = SNDLVL_GUNFIRE, sound = "weapons/cz52/fire.wav" })
sound.Add({ name="Weapon_ELITE.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/elite/elite-1.wav" })
sound.Add({ name="Weapon_FAMAS.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/famas/famas-1.wav" })
sound.Add({ name="Weapon_g36c.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/G36C/G36C-unsil.wav" })
sound.Add({ name="Weapon_G3SG1.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/g3sg1/g3sg1-1.wav" })
sound.Add({ name="Weapon_Galil.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/galil/galil-1.wav" })
sound.Add({ name="Weapon_Glock.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/glock/glock18-1.wav" })
sound.Add({ name="Weapon_mp5k.Burst", channel=CHAN_WEAPON, pitch={98,101}, volume=0.95, level = SNDLVL_GUNFIRE, sound = "weapons/mp5k/mp5k_fireburst1.wav" })
sound.Add({ name="Weapon_mp5k.Single", channel=CHAN_WEAPON, pitch={98,101}, volume=0.95, level = SNDLVL_GUNFIRE, sound = "weapons/mp5k/mp5k_fire1.wav" })
sound.Add({ name="Weapon_MP5Navy.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/mp5navy/mp5-1.wav" })
sound.Add({ name="Weapon_P90.Single", channel=CHAN_WEAPON, pitch=PITCH_NORM, volume=1.0, level = SNDLVL_NORM, sound = "weapons/p90/p90-1.wav" })
sound.Add({ name="Weapon_Shotgun.Empty", channel=CHAN_WEAPON, pitch={95,100}, volume=0.7, level = SNDLVL_NORM, sound = "weapons/shotgun/shotgun_empty.wav" })


sound.Add({ name="Weapon_Shotgun.Special1", channel=CHAN_ITEM, pitch=1, volume=0.7, level = SNDLVL_NORM, sound = "weapons/shotgun/shotgun_cock.wav" })
sound.Add({ name="Weapon_remi870.Single", channel=CHAN_WEAPON, pitch={98,101}, volume=0.9, level = SNDLVL_GUNFIRE, sound = "weapons/remi870/fire.wav" })
sound.Add({ name="Weapon_remi870.Special1", channel=CHAN_ITEM, pitch=1, volume=0.8, level = SNDLVL_NORM, sound = "weapons/remi870/cock.wav" })
